
version: '3.4'

x-common-env-variables: &common-env-variables
    RABBITMQ_ADDRESS: rabbitmq
    PYTHONUNBUFFERED: 1

x-base-worker: &base-worker
    build:
        context: .
        dockerfile: ./Dockerfile
    command: "new_main.py"
    depends_on:
        - rabbitmq
    volumes:
        - ./:/app

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.9-management
        ports:
            - 5672:5672
            - 15672:15672

    answers_csv_parser_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: answers_csv_parser
            WORKER_ID: 0

    answers_csv_parser_1:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: answers_csv_parser
            WORKER_ID: 1

    answers_csv_parser_2:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: answers_csv_parser
            WORKER_ID: 2

    answers_csv_parser_3:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: answers_csv_parser
            WORKER_ID: 3

    answers_csv_parser_4:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: answers_csv_parser
            WORKER_ID: 4

    answers_csv_parser_5:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: answers_csv_parser
            WORKER_ID: 5

    answers_csv_parser_6:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: answers_csv_parser
            WORKER_ID: 6

    questions_csv_parser_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: questions_csv_parser
            WORKER_ID: 0

    questions_csv_parser_1:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: questions_csv_parser
            WORKER_ID: 1

    questions_csv_parser_2:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: questions_csv_parser
            WORKER_ID: 2

    questions_csv_parser_3:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: questions_csv_parser
            WORKER_ID: 3

    questions_csv_parser_4:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: questions_csv_parser
            WORKER_ID: 4

    questions_csv_parser_5:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: questions_csv_parser
            WORKER_ID: 5

    questions_csv_parser_6:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: questions_csv_parser
            WORKER_ID: 6

    filter_by_score_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_score
            WORKER_ID: 0

    filter_by_score_1:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_score
            WORKER_ID: 1

    filter_by_sentiment_analysis_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_sentiment_analysis
            WORKER_ID: 0

    filter_by_sentiment_analysis_1:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_sentiment_analysis
            WORKER_ID: 1

    filter_by_sentiment_analysis_2:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_sentiment_analysis
            WORKER_ID: 2

    filter_by_sentiment_analysis_3:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_sentiment_analysis
            WORKER_ID: 3

    filter_by_sentiment_analysis_4:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_sentiment_analysis
            WORKER_ID: 4

    filter_by_sentiment_analysis_5:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_by_sentiment_analysis
            WORKER_ID: 5

    calculate_percentage_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: calculate_percentage
            WORKER_ID: 0

    score_by_user_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: score_by_user
            WORKER_ID: 0

    score_by_user_1:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: score_by_user
            WORKER_ID: 1

    score_by_user_2:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: score_by_user
            WORKER_ID: 2

    filter_top_10_by_score_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: filter_top_10_by_score
            WORKER_ID: 0

    join_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: join
            WORKER_ID: 0

    join_1:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: join
            WORKER_ID: 1

    join_2:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: join
            WORKER_ID: 2

    join_3:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: join
            WORKER_ID: 3

    score_by_tag_and_year_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: score_by_tag_and_year
            WORKER_ID: 0

    score_by_tag_and_year_1:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: score_by_tag_and_year
            WORKER_ID: 1

    score_by_tag_and_year_2:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: score_by_tag_and_year
            WORKER_ID: 2

    score_by_tag_and_year_3:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: score_by_tag_and_year
            WORKER_ID: 3

    top_10_tags_0:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_TASK: top_10_tags
            WORKER_ID: 0

